- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo

  tasks:
    - name: Install Apache server
      yum:
        name: httpd
        state: present

    - name: Install NGINX
      yum:
        name: nginx
        state: present
